//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учет_посещаемости
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id_user { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_student { get; set; }
        public Nullable<int> Type_User { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual User_type User_type { get; set; }
    }
}
